class Contact{constructor(){this.id=0;this.name="";this.phone="";this.date="";}}
const entity={save:false,contacts:[],idContactToRemove:0,init(){entity.save=false;$("#txtValue").attr("disabled",true);$($("input[type=checkbox]")[0]).prop("checked",false);entity.contacts=[];entity.idContactToRemove=0;entity.readContacts();},toggleSave:()=>{entity.save=!entity.save;$("#txtValue").attr("disabled",!entity.save)
$("#txtValue").val("")
if(!entity.save){$("#txtValue").removeClass("error");$("#name-validation").addClass("d-none");}},readContacts:()=>{entity.contacts=JSON.parse(localStorage.getItem('contacts'));if(!entity.contacts){entity.contacts=[];}
entity.showContacts();},saveContacts:()=>{localStorage.setItem('contacts',JSON.stringify(entity.contacts));},showContacts:()=>{var cardTemplate=$("#contact-card-template");var cardContainer=$(".contacts-list");$(".delete-contact").removeClass("blocked");$(".contacts-list").removeClass("empty");cardContainer.html("");if(entity.contacts.length==0){$(".delete-contact").addClass("blocked");$(".contacts-list").addClass("empty");cardContainer.html($("#empty-template").html());return;}
for(var i=0;i<entity.contacts.length;i++){var contact=entity.contacts[i];var card=cardTemplate.html().replaceAll("{{id}}",contact.id).replaceAll("{{name}}",contact.name).replaceAll("{{phone}}",contact.phone).replaceAll("{{date}}",contact.date);cardContainer.append(card);}},clearValidations:()=>{$("#txtPhone").removeClass("error");$("#txtValue").removeClass("error");$("#phone-validation").addClass("d-none");$("#name-validation").addClass("d-none");},validate:(ohone)=>{let isPhoneValid=true;let isNameValid=true;if($("#txtPhone").val()==""){$("#txtPhone").addClass("error");$("#phone-validation").removeClass("d-none");isPhoneValid=false;}
if(entity.save){if($("#txtValue").val()==""){$("#txtValue").addClass("error");$("#name-validation").removeClass("d-none");isNameValid=false;}}
return isPhoneValid&&isNameValid;},next:()=>{entity.clearValidations();let phone=$(".iti__selected-dial-code").html().replace("+","")+$("#txtPhone").val();let isValid=entity.validate(phone);if(!isValid){return;}
if(entity.save){let contact=entity.contacts.filter(s=>s.phone==phone)[0];if(!contact){contact=new Contact();contact.id=(new Date()).getTime();contact.phone=phone;}
contact.name=$("#txtValue").val();contact.date=(new Date()).toLocaleString();entity.contacts=[contact,...entity.contacts.filter(s=>s.id!=contact.id)];entity.saveContacts();entity.showContacts();}
entity.openChat(phone);},goToContact:(id)=>{let phone=entity.contacts.filter(s=>s.id==id)[0].phone;entity.openChat(phone);},openChat:(phone)=>{phone=phone.replaceAll(" ","").replaceAll("-","");window.location.href="https://api.whatsapp.com/send?phone="+phone;},openDialog:()=>{$(".window-overlay").removeClass("d-none");},closeDialog:()=>{entity.idContactToRemove=0;$(".window-overlay").addClass("d-none");},openRemoveContactDialog:(id)=>{entity.idContactToRemove=id;$(".window-title").html(entity.contacts.filter(s=>s.id==id)[0].name);$(".window-content-text").html("Tem certeza que deseja excluir esse contato?");entity.openDialog();},openLinkDialog:()=>{$(".link-container").removeClass("d-none");},closeLinkDialog:()=>{$(".link-container").addClass("d-none");},openRemoveAllContactsDialog:()=>{if(entity.contacts.length==0){return;}
entity.idContactToRemove=-1;$(".window-title").html("CONTATOS");$(".window-content-text").html("Tem certeza que deseja excluir todos os contatos?");entity.openDialog();},removeContact:()=>{if(entity.idContactToRemove==0){return;}
if(entity.idContactToRemove==-1){entity.contacts=[];}
else{entity.contacts=entity.contacts.filter(s=>s.id!=entity.idContactToRemove);}
entity.idContactToRemove=0;entity.saveContacts();entity.showContacts();entity.closeDialog();}}